## BasicPlugin Settings, Like the Prefix Etc.
Plugin:
  Prefix: "&f[&8DarkSkies&f]"
## All The Features Of The Plugin.
Features:
  ## The BackPack Feature.
  Backpack:
    ## This Determinate What Texture The BackPack Has.
    CustomModelData:
      - 10124
      - 1
  ## This Is For The Fishing Feature.
  Fishing:
    ## This Enables the fishing feature
    Enabled: true
    ## Enables and disables the vanilla loot
    RemoveVanillaLoot: true
    ## If you set it to -1 it means it is disabled.
    ChanceOfGettingAnyLoot: -1
    ## In here you can set loot tables
    LootTables:
      ## Common is the name of the loot table you can add more tables by copying the table.
      Common:
        ## This is the index when you want to add an item to the loot table that is randomly distributed. You just count 1 up.
        1:
          Material: "DIAMOND_PICKAXE"
          ItemName: "&aGoodPickaxe"
          CustomModelData: -1
          Durability: 2
        2:
          Material: "DIAMOND_PICKAXE"
          ItemName: "&aBetterPickaxe"
          CustomModelData: -1
          Durability: 2
    ## here you can set what tools have custom drop's
    Tools:
      ## Here you display the name you see in big (Item Name) NOT the material name.
      Fishing Rod:
        CustomModelData: -1
        LootTable: "Common"
  HelpOverride:
   Enabled: true
   StaffPermission: "DarkSkies.StaffHelp"
   PlayerHelp:
     - "&8---{ &b&lPlayer Help &8}---"
     - "&7- Add Something Here"
     - "&7- And Add Something Here"
   StaffHelp:
     - "&8---{ &c&lStaff Help &8}---"
     - "&7- Add Something Here"
     - "&7- And Add Something Here"
  Stones:
    WaterMarkLine: 0
    WaterMarkLore: "&f"
    TierLine: 2
    StoneSlots:
      - 9
      - 10
    ## Stones:
    FireProtStone: "&c&lFire Stone"
    Nightvisstone: "&2Night Stone"
    FallprotStone: "&fFalling Stone"
    Foodstone: "&1&lFeeding Stone"
    Healthstone: "&c&lHealth Stone"
    Speedstone: "&b&lSpeed Stone"
    HasteStone: "&6&lHasty Stone"
## All The Messages Used Inside The Plugin.
Messages:
  No-BackPack: "&cYou Don't Have an backpack Equipped!"
  GetItem: "&a&lYou Found An Hidden Treasure!, You Found: %ITEM%"