## BasicPlugin Settings, Like the Prefix Etc.
Plugin:
  Prefix: "&f[&8DarkSkies&f]"
## All The Features Of The Plugin.
Features:
  ## The BackPack Feature.
  Backpack:
    ## This Determinate What Texture The BackPack Has.
    CustomModelData: 10124
  ## This Is For The Fishing Feature.
  Fishing:
    LootTables:
      Common:
        - 1:
            Material: "DIAMOND_PICKAXE"
            ItemName: "&aGoodPickaxe"
            CustomModelData: -1
            Durability: 2
        - 2:
            Material: "DIAMOND_PICKAXE"
            ItemName: "&aBetterPickaxe"
            CustomModelData: -1
            Durability: 2
    Tools:
      Fishing Rod:
        CustomModelData: -1
        LootTable: "Common"
## All The Messages Used Inside The Plugin.
Messages:
  No-BackPack: "&cYou Don't Have an backpack Equipped!"